spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iot_hub_dev
    username: dev_iot_user
    password: dev_iot_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true