spring:
  datasource:
    core:
      jdbc-url: jdbc:postgresql://localhost:5431/iothubcore
      username: core_app
      password: core_app_password
      driver-class-name: org.postgresql.Driver
    timeseries:
      jdbc-url: jdbc:postgresql://localhost:5433/iothubtimeseries
      username: ts_app
      password: ts_app_password
      driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: c039fa094303399671f60a50102386488f3faa98b0d5478d1ad75dd7b2ddb723
  expiration: 28800
accounts-config:
  delete-account-delay-days: ${DELETE_ACCOUNT_DELAY_DAYS:30}
  verify-account-delay-hours: ${VERIFY_ACCOUNT_DELAY_HOURS:24}
  password-reset-delay-hours: ${PASSWORD_RESET_DELAY_HOURS:2}
logging:
  level:
    root: INFO
    com.pfitztronic.iothub: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE